apiVersion: v1
kind: ConfigMap
metadata:
  name: shoulders-platform-config
  namespace: flux-system
data:
  SHOULDERS_PROFILE: small
  SHOULDERS_POSTGRES_INSTANCES: "1"
  SHOULDERS_KAFKA_REPLICAS: "1"
  SHOULDERS_KAFKA_MIN_ISR: "1"
  SHOULDERS_KAFKA_STORAGE: 1Gi
  SHOULDERS_PROMETHEUS_RETENTION: 6h
  SHOULDERS_PROMETHEUS_RETENTION_SIZE: 512MiB