apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  dependsOn:
    - name: dex
      namespace: dex
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "83.7.0"
  values:
    grafana:
      assertNoLeakedSecrets: false
      sidecar:
        dashboards:
          searchNamespace: ALL
      grafana.ini:
        server:
          root_url: http://${SHOULDERS_GRAFANA_HOST}
        auth:
          disable_login_form: false
        auth.generic_oauth:
          enabled: true
          name: Dex
          allow_sign_up: true
          client_id: grafana
          client_secret: grafana-dex-secret
          scopes: openid email profile groups offline_access
          auth_url: https://${SHOULDERS_DEX_HOST}/auth
          token_url: http://dex.dex.svc.cluster.local:5556/token
          api_url: http://dex.dex.svc.cluster.local:5556/userinfo
          use_pkce: true
          role_attribute_path: "contains(groups[*], 'admin') && 'Admin' || contains(groups[*], 'developers') && 'Editor' || 'Viewer'"
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki.observability:3100
          access: proxy
          jsonData:
            derivedFields:
              - datasourceUid: tempo
                matcherRegex: "traceID=(\\w+)"
                name: TraceID
                url: "$${__value.raw}"
        - name: Tempo
          type: tempo
          url: http://tempo.observability:3100
          access: proxy
          jsonData:
            tracesToLogsV2:
              datasourceUid: "Loki"
              tags: ["job", "instance", "pod", "namespace"]
            tracesToMetrics:
              datasourceUid: "Prometheus"
              tags: [{ key: "service.name", value: "service" }, { key: "job" }]
    prometheus:
      prometheusSpec:
        retention: 24h
        retentionSize: 1GiB
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
