apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  url: https://git.deuxfleurs.fr/Deuxfleurs/garage.git
  ref:
    commit: a2c797000fbcc68fcfd866a4d9e3375ebfdc0d99
