apiVersion: v1
kind: Secret
metadata:
  name: oidc
  namespace: headlamp
type: Opaque
stringData:
  clientID: kubernetes
  clientSecret: headlamp-dex-secret
  issuerURL: https://${SHOULDERS_DEX_HOST}
  scopes: openid,email,profile,groups
  callbackURL: http://${SHOULDERS_HEADLAMP_HOST}/oidc-callback
  validatorClientID: kubernetes
  validatorIssuerURL: https://${SHOULDERS_DEX_HOST}
  usePKCE: "true"
