apiVersion: v1
kind: Secret
metadata:
  name: oidc
  namespace: headlamp
type: Opaque
stringData:
  clientID: kubernetes
  clientSecret: headlamp-dex-secret
  issuerURL: https://dex.127.0.0.1.sslip.io
  scopes: openid,email,profile,groups
  callbackURL: http://headlamp.localhost/oidc-callback
  validatorClientID: kubernetes
  validatorIssuerURL: https://dex.127.0.0.1.sslip.io
  usePKCE: "true"
