apiVersion: v1
kind: Secret
metadata:
  name: dex-tls
  namespace: kube-system
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDdTCCAl2gAwIBAgIUViUyHeX9NlmRd0WLbAd3rtAGRAYwDQYJKoZIhvcNAQEL
    BQAwGzEZMBcGA1UEAwwQc2hvdWxkZXJzLWRleC1jYTAeFw0yNjAzMTExNzA3NTRa
    Fw0zNjAzMDgxNzA3NTRaMBgxFjAUBgNVBAMMDXNob3VsZGVycy1kZXgwggEiMA0G
    CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDO/npIlsFQNhuCvpY5XYj2avUzQA7D
    lzSLGY4OUtSxrpCsMasEtmcEZx9/o4/I2c2GKe+dc80cKSCDmYrKbemLMkoekmUm
    A+OglJLrSDPdw7VaRKBiukIiGI/jkg378CxYezcgAhL2y00+R1grhxXiNHIDM8w2
    /gP9COpUHzeGRkocZs5Lhu99AYr0AKdJ14Pq93g8GK7jmQLzQX7LWn9pcUOfABAd
    hrxCYqnm+4beHlkPBONjOa66RX4E5l8jyu9UmhWNgtzpTXRgcp8MIvDrz3xs4LGc
    Xt+nVTvbfsXPudgvJki91+Sc7hCM1LlnGeMHjfYu4tsRxnZQTkvrh8pHAgMBAAGj
    gbMwgbAwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMEkGA1Ud
    EQRCMECCFmRleC4xMjcuMC4wLjEuc3NsaXAuaW+CC2RleC5kZXguc3ZjghlkZXgu
    ZGV4LnN2Yy5jbHVzdGVyLmxvY2FsMB0GA1UdDgQWBBTANQBJYXr8KlGDo+P51kHY
    Y/MK4jAfBgNVHSMEGDAWgBTWED30YiksTlkliQ8p5YHwE0mEdDANBgkqhkiG9w0B
    AQsFAAOCAQEAlH9Rdzrfz6N2Xi54kBM8HZEglXEZfLzbwOTuOdzSsOSjS2Iyoi8M
    OGXgaMGZgRCHVnVvNy14knBtlvGFFUP7anaiJF3IYyTJADWPGJMBTzY4c04GYxYa
    aJudQYY7BXnRSkUqgLgufdaJ1Hoqw7W3EkKimDOIUH5pDRicR8U3unpYcIXrhshd
    Op1tZLAuiDlFyocmWUPxPLECVr/AKlVzcsNsNU4oOnLphkKOajyjCs9xCx/jIFzs
    tbJwJdCEHFFQvcDgDofAPAmdzJ6JV7Ok2kXUYT7wEFeHcTPd6nbtitbWiSa1RtCx
    7R6GSBDNcnJPS6e3GXp53b8ftKhQiQsDzw==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDO/npIlsFQNhuC
    vpY5XYj2avUzQA7DlzSLGY4OUtSxrpCsMasEtmcEZx9/o4/I2c2GKe+dc80cKSCD
    mYrKbemLMkoekmUmA+OglJLrSDPdw7VaRKBiukIiGI/jkg378CxYezcgAhL2y00+
    R1grhxXiNHIDM8w2/gP9COpUHzeGRkocZs5Lhu99AYr0AKdJ14Pq93g8GK7jmQLz
    QX7LWn9pcUOfABAdhrxCYqnm+4beHlkPBONjOa66RX4E5l8jyu9UmhWNgtzpTXRg
    cp8MIvDrz3xs4LGcXt+nVTvbfsXPudgvJki91+Sc7hCM1LlnGeMHjfYu4tsRxnZQ
    Tkvrh8pHAgMBAAECggEAB/7dc1tbaUFFy8WX4Oxjg307LnkdeOGo1mysx5HchGaF
    URl0DTEMhqeDGHeVcME1BqctCcx00k8mYd729P3M5SMSqN6nyJGi48uJZ0w5MKpE
    IZIADgA62L1RJY25O4+Z7usHhJV/7QeKWsr/tWK47i1vb/86tq8WMVp8TraL+wQ/
    OIt5fHQApzU0tH1AQgdOs5JvXzQPaV8eEWlfrA3YE0bCTWXG94bQIQBjhWAMtfr7
    JZ5eVHvL4RskGKWAEj4Y0XfkYa3C5f60YSO6co47UlYVl37GE6jYUPyAQ9CTZMKq
    LdB0vV3pATRIqSzGP8qUU5GKBL8xX6L9MWzCv06ttQKBgQD30UHCPRbvP0H0gvWO
    dt7SbU3Gm17iarg6pVwWUXlt3Yy1Xvud3IYwHdVKgF62XgA/aAkwRQRsYkY+xtbx
    XTTn7YAVtFfMDg6V2DF6qCnJkVSkvYj83vMSw3bTyyqvc0OMwcrxITbatzxAStr0
    wb3ZonzW9J0rYs79ge+oJnCswwKBgQDV1CaCojvpD+bvNdawVTcDngJjCgEukjUG
    vxzEGncgTHP+orVHS5eQJ/ArmQRB6Pc0VuPW1JNe3v96udQYtFDaS0VL40QwFBFg
    FxVyblIORHGluIISCQVC3tS5PGKG+zlFdn67FkSsWCPLwwTMbQy9/ZQFQosL4HtO
    fmJDSfokLQKBgQDlU6EdxXh+x7QaOEJSptAGPJ4Xp1oD/qwjoTh5csYDFF2Mzavc
    5uDKkCD8A5UiABUMmBLAt22jesH0f/8SdqVp5s97xlrk+zEmG12WWx3oaPPCS58E
    GrEn8Pf6gG0s1WZyUDekMo9XkO9Rs7OxgcRVLNeH9++l4ZcY43BK09+7DwKBgHBn
    ZJMZW2sJu/kVkTUCprfVESYk9TgZDZztS97elq644eUCfU7sMtFJ3VvdxTosj/7I
    il69QncFvMEz/IW8DCCkntnkr0yiz/t2RwTvb10mp6NZGa8HZOehIav6TUTtvU6B
    mt8YNqNuderAKr6XuLILIgudzmBA8jDyCQ+cTM1FAoGBAJ4i2XVboKNtqs5h7/n3
    Nzb/oCaqTnudMFe4IlvyqvqrlF4WX6YwZ7ywtjTcUvBxFTFYme9Qa4YXyJChQka9
    xgMD8qwqj+9Y+oLq3UMscLQ0BPUnTajixfQURctjwyDMhldODorflUtLE1RmVm2G
    sKE1VD6ALlmQ+8MKT2TmP2Ha
    -----END PRIVATE KEY-----