apiVersion: apiserver.config.k8s.io/v1
kind: AuthenticationConfiguration
jwt:
  - issuer:
      url: https://dex.127.0.0.1.sslip.io
      discoveryURL: https://dex.dex.svc.cluster.local/.well-known/openid-configuration
      certificateAuthority: |
        -----BEGIN CERTIFICATE-----
        MIIDFzCCAf+gAwIBAgIUb8BLrNjs+mKY2tQnSzQOrT2uPWEwDQYJKoZIhvcNAQEL
        BQAwGzEZMBcGA1UEAwwQc2hvdWxkZXJzLWRleC1jYTAeFw0yNjAzMTExNzA3NTRa
        Fw0zNjAzMDgxNzA3NTRaMBsxGTAXBgNVBAMMEHNob3VsZGVycy1kZXgtY2EwggEi
        MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3TU/OUmcjz5wtYhjIihYTFDbR
        l2Kbnz8VV97ulgdQuJhkahJuIT1XjiPF1aqvgpOr6zDmZjRBc05es84V4hMUyoxp
        HXf94vTQrn3r7KvM9+0d80SR2jfSBTi/60cVA10LQEboANdBrhsl26BgbvXYG7f7
        iOgv0L84KHdfpNkF6QoCh9YkYBnk+gKips0/gN3hDnYK/w1/ovzqohvJuQYZdPeA
        4/G9OFvnoesZuvhaspPPufKZItaSf2vyB4yhjVzm8DXXDVtSNmHaS+wt06iXX80i
        C1J3TWnEXt0pXHwwe0jrU75VKe55GqFo7+3Q1lDXW1uK4GAsDfgAe27ZlDi3AgMB
        AAGjUzBRMB0GA1UdDgQWBBTWED30YiksTlkliQ8p5YHwE0mEdDAfBgNVHSMEGDAW
        gBTWED30YiksTlkliQ8p5YHwE0mEdDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3
        DQEBCwUAA4IBAQClgiqXKpjrG7mcfNvEvYsNvZxbg6sYSM0pQEmn/XExZUMJP3eQ
        cdZyouF+21lRxG6EW+88EMblLa+zXV4t2Qp1qvJS97BmHi/vZ2HMIuXqpPBCkpsB
        5qGCmiw5rshmmrhAFPqU2aPY8eBIjKY91fMNo1yG/8slACobtEb6iLRE/hztpJNI
        bpYCT307xRJ9NU4rNE7f+TMPHh1we7wn/wwZbQvGDMUFp23UMALEUde1sy5D0dwG
        xgJ5xtMuzDGeYfso60/6MCUWwJTQ15pZhtEpiGdf62/ITm4APeBImQ/lVWibtsBi
        MuKNJzZSHEA6nwbAmitpmp34vbkMTrjcVlpX
        -----END CERTIFICATE-----
      audiences:
        - kubernetes
      audienceMatchPolicy: MatchAny
    claimMappings:
      username:
        claim: email
        prefix: ""
      groups:
        claim: groups
        prefix: ""
    userValidationRules:
      - expression: "!user.username.startsWith('system:')"
        message: "username cannot use reserved system: prefix"