apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  values:
    grafana:
      additionalDataSources: []
    prometheus:
      prometheusSpec:
        retention: ${SHOULDERS_PROMETHEUS_RETENTION}
        retentionSize: ${SHOULDERS_PROMETHEUS_RETENTION_SIZE}